sudo: required

language: node_js
node_js:
  - "8"


services:
  - docker

before_install:
  - npm install


script:
  - npm run build


deploy:
  provider: script
  script: bash docker_release
  skip_cleanup: true
  on:
    branch: master
